version: '3'
services:
  customercommandside:
    build: ../customers-service/
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://$DOCKER_HOST_IP/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: $DOCKER_HOST_IP:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: $DOCKER_HOST_IP:2181
