version: '3'
services:
  customercommandside:
    build: ../customers-service/
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://$DOCKER_HOST_IP/eventuate
      SPRING_DATASOURCE_USERNAME: eventuate
      SPRING_DATASOURCE_PASSWORD: eventuate
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: $DOCKER_HOST_IP:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: $DOCKER_HOST_IP:2181
