customercommandside:
  build: ../customers-service/
  ports:
    - "8081:8080"
  environment:
    EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
    EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}
